### ISSUE TITLE
Requirements cant be installed 

### ISSUE THREAD

**Issue by Bratwurscht** [shownotes/snotes20-restapi#32]
Cant install requirements for commit b107ff79405bfdb7da392a81d63c4fb0f24510f3
Error in installing scipy with pip
Additional manual installation of package python-scipy, python-scipy-dbg does not work

**Comment by Drake81** [comment]
Fixed by commit 50f708e3e5a1a

Caused by pip freeze. 
python-scipy must be installed before scikit-learn.

**Comment by Drake81** [comment]
@Bratwurscht
Please, try again after installing the following packages[1].
```sh
sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
```
Give me a hint, which one was needed for your setup. This will help to improve the docs.

[1] https://stackoverflow.com/questions/11114225/installing-scipy-and-numpy-using-pip

**Comment by Bratwurscht** [comment]
After an endless installation with pip everything works fine ;)
Both installation steps were required. I will update Readme.md with your instructions.

**Comment by Drake81** [comment]
:+1:
